package com.vladislav.shumilov.launch_domain.model

interface Launch {
    var flight_id: String?
    var startEnd: String?
    var launch_year: Int?
    var launch_date_utc: String?
    var tbd: Boolean?
    var rocket_id: String?
    var core_serial: String?
    var land_success: Boolean?
    var landing_intent: Boolean?
    var landing_type: String?
    var landing_vehicle: String?
    var cap_serial: String?
    var core_flight: Int?
    var block: Int?
    var gridfins: Boolean?
    var legs: Boolean?
    var core_reuse: Boolean?
    var capsule_reuse: Boolean?
    var fairings_reused: Boolean?
    var fairings_recovery_attempt: Boolean?
    var fairings_recovered: Boolean?
    var fairings_ship: String?
    var site_id: String?
    var site_name: String?
    var payload_id: String?
    var norad_id: Int?
    var customer: String?
    var nationality: String?
    var manufacturer: String?
    var payload_type: String?
    var orbit: String?
    var reference_system: String?
    var regime: String?
    var longitude: Float?
    var semi_major_axis_km: Float?
    var eccentricity: Float?
    var periapsis_km: Float?
    var apoapsis_km: Float?
    var inclination_deg: Float?
    var period_min: Float?
    var lifespan_years: Int?
    var epoch: String?
    var mean_motion: Float?
    var raan: Float?
    var launch_success: Boolean?
}